# SuperbVote configuration
# A superb vote plugin made by Tux.
#
# https://minecraft.minimum.io/wiki/SuperbVote

# Database configuration.
# Currently supported: "json".
storage:
  database: json
  json:
    file: votes.json
  mysql:
    host: 127.0.0.1
    username: root
    password: topsecret
    database: superbvote
    table: votes
    read-only: false

# General vote configuration.
votes:
  # At least this many seconds need to pass before allowing another vote (per-service). This will apply per service.
  # Default: 3600 seconds (1 hour)
  cooldown-per-service: 3600

# Rewards. This is the main section you will need to edit. Ordering is important.
rewards:
  # Example of matchers.
  - if:
      permission: superbvote.test
      chance: 100
      service: SpecialService
    commands:
    - give %player% diamond 4
    player-message: "&aThanks for meeting nearly impossible conditions, you have been rewarded with 4 diamonds and $1000."
    broadcast-message: "&a%player% got really lucky and was rewarded with 4 diamonds and $1000!"
  # Default rewards are defined by having no preconditions. Place it at the bottom of the config.
  - if: {}
    commands:
    - eco give %player% 1000
    player-message: "&aThanks for voting for us on %service%, you have been rewarded with $1000."
    broadcast-message: "&a%player% has voted for us on %service% and was rewarded with $1000!"

# Whether or not players need to be online to vote. If set, offline player votes are queued for when the player next logs in.
require-online: true

# Broadcast settings:
broadcast:
  # Should we broadcast votes at all?
  enabled: true

  # Should we broadcast queued votes?
  queued: true

# Vote reminder.
vote-reminder:
  message: "&cDon't forget to vote for us! You currently have &a%votes%&c votes."
  on-join: true
  repeat: 180

# Controls the /sv <top/leaderboard> command.
leaderboard:
  # Supported: text, scoreboard
  display: text

  # The text format supports pagination.
  text:
    per-page: 10

  # Control the scoreboard.
  scoreboard:
    title: Top voters
    max: 10